export default {
  ArrowImage: require('../assets/images/arrow/path6.png'),
  CartImage: require('../assets/images/cart/cart.png'),
  CrabImage: require('../assets/images/crab/group6.png'),
  CrossImage: require('../assets/images/cross/cross.png'),
  EggImage: require('../assets/images/egg/group1.png'),
  FishImage: require('../assets/images/fish/group8.png'),
  GrayLikeImage: require('../assets/images/grayLike/icons8Like.png'),
  GrayLikeSmallImage: require('../assets/images/grayDislike/icons8Like.png'),
  MaskCopyImage: require('../assets/images/maskCopy/maskCopy.png'),
  MaskCopy1Image: require('../assets/images/maskCopy1/maskCopy.png'),
  MaskCopy2Image: require('../assets/images/maskCopy2/maskCopy.png'),
  MaskCopy3Image: require('../assets/images/maskCopy3/maskCopy.png'),
  MaskCopy4Image: require('../assets/images/maskCopy4/maskCopy.png'),
  MaskCopy5Image: require('../assets/images/maskCopy5/maskCopy.png'),
  MenuImage: require('../assets/images/menu/menu.png'),
  RectangleImage: require('../assets/images/rectangleImage/rectangle.png'),
  RedLikeImage: require('../assets/images/redLike/iconsRedLike.png'),
  SearchImage: require('../assets/images/search/search.png'),
  TitleImage: require('../assets/images/titleImage/title.png'),
  WheatImage: require('../assets/images/wheat/group7.png'),
};
