import {ScaledSheet} from 'react-native-size-matters';
import constants from '../../constants';

const styles = ScaledSheet.create({
  container: {
    flex: 1,
  },
  flex1: {flex: 1},
  marginPadding: {
    marginHorizontal: '16@ms',
    paddingVertical: '16@ms',
  },
  flexWithDirection: {
    flexDirection: 'row',
    flex: 1,
  },
  TitleImage: {
    flex: 1.2,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  titleImageStyle: {
    height: '52@ms',
    width: '60@ms',
  },
  titleWrapper: {
    flex: 3,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  titleText: {
    fontFamily: 'Inter-Medium',
    fontSize: '18@ms',
    lineHeight: '18@ms',
    color: 'rgb(53,53,53)',
  },
  crossButtonWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
    paddingRight: '5@ms',
  },
  crossButtonStyle: {
    height: '30@ms',
    width: '30@ms',
  },
  discriptionTextWrapper: {
    justifyContent: 'center',
    paddingVertical: '10@ms',
    alignItems: 'center',
  },
  discriptionText: {
    fontFamily: 'Inter-Regular',
    fontSize: '14@ms',
    lineHeight: '20@ms',
    color: 'rgb(119,119,119)',
    textAlign: 'left',
  },
  addToWrapper: {
    flexDirection: 'row',
    paddingVertical: '10@ms',
    alignItems: 'center',
  },
  addToText: {
    fontSize: '14@ms',
    lineHeight: '14@ms',
    fontFamily: 'Inter-Regular',
    color: 'rgb(119,119,119)',
    paddingLeft: '13@ms',
  },
  contantWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    borderColor: 'rgb(199,199,199)',
    borderTopWidth: '1@ms',
    borderBottomWidth: '1@ms',
    paddingVertical: '16@ms',
    marginVertical: '8@ms',
  },
  flexCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contantImageStyle: {
    height: '32@ms',
    width: '32@ms',
    marginBottom: '8@ms',
  },
  contantText1: {
    fontSize: '12@ms',
    lineHeight: '12@ms',
    fontFamily: 'Inter-Regular',
    color: 'rgb(119,119,119)',
    textAlign: 'center',
  },
  margin20: {marginTop: '20@ms'},
  headingText: {
    fontFamily: 'Inter-Medium',
    fontSize: '16@ms',
    lineHeight: '16@ms',
    color: 'rgb(53,53,53)',
  },
  detailText: {
    fontFamily: 'Inter-Regular',
    fontSize: '14@ms',
    lineHeight: '14@ms',
    color: 'rgb(119,119,119)',
    paddingVertical: '12@ms',
  },
  flexRow: {flexDirection: 'row'},
  flexRowAlignCenter: {flexDirection: 'row', alignItems: 'center'},
  radioButtonSelectWrapper: {
    height: '20@ms',
    width: '20@ms',
    borderRadius: '10@ms',
    borderWidth: '2@ms',
    justifyContent: 'center',
    alignItems: 'center',
  },
  borderOrange: {borderColor: constants.colors.OrangeColor},
  borderWhiteTwo: {borderColor: constants.colors.WhiteTwo},
  radioButtonInner: {
    height: '10@ms',
    width: '10@ms',
    backgroundColor: constants.colors.OrangeColor,
    borderRadius: '5@ms',
  },
  radioButtonText: {
    fontFamily: 'Inter-Regular',
    fontSize: '15@ms',
    lineHeight: '15@ms',
    color: 'rgb(53,53,53)',
    paddingLeft: '15@ms',
  },
  flexRowWithMarginA: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: '20@ms',
  },
  flexRowMarginTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: '20@ms',
  },
  checkBoxWrapper: {
    height: '20@ms',
    width: '20@ms',
    borderRadius: '5@ms',
    borderColor: constants.colors.OrangeColor,
    borderWidth: '2@ms',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkBoxText: {
    fontFamily: 'Inter-Regular',
    fontSize: '15@ms',
    lineHeight: '15@ms',
    color: 'rgb(53,53,53)',
    paddingLeft: '15@ms',
  },
  flexRowVertical: {flexDirection: 'row', marginVertical: '20@ms'},
  uploadImageButton: {
    height: '30@ms',
    width: '165@ms',
    borderRadius: '5@ms',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: constants.colors.WhiteTwo,
  },
  uploadButtonText: {
    fontFamily: 'Inter-Regular',
    fontSize: '14@ms',
    lineHeight: '14@ms',
    color: 'rgb(53,53,53)',
  },
  deleteButton: {
    marginTop: '16@ms',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteButtonText: {
    fontFamily: 'Inter-Regular',
    fontSize: '14@ms',
    lineHeight: '14@ms',
    color: constants.colors.OrangeColor,
  },
  counterWrapper: {
    flexDirection: 'row',
    width: '73@ms',
    height: '28@ms',
    borderWidth: '1@ms',
    borderColor: constants.colors.WhiteTwo,
    borderRadius: '5@ms',
  },
  addMinusText: {
    fontFamily: 'Inter-Medium',
    fontSize: '12@ms',
    lineHeight: '12@ms',
    textAlign: 'center',
    color: constants.colors.OrangeColor,
  },
  CounterWrapperCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgb(255,201,159)',
  },
  CountText1: {
    fontFamily: 'Inter-Medium',
    fontSize: '12@ms',
    lineHeight: '12@ms',
    textAlign: 'center',
    color: constants.colors.BlackLight,
  },
  bottomButtonWrapper: {
    borderColor: constants.colors.WhiteTwo,
    borderTopWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomButton: {
    height: '50@ms',
    width: '343@ms',
    backgroundColor: constants.colors.OrangeColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '5@ms',
    marginVertical: '20@ms',
  },
  bottomButtonText: {
    fontFamily: 'Inter-Medium',
    fontSize: '16@ms',
    lineHeight: '16@ms',
    color: '#ffffff',
    textAlign: 'center',
  },
  inputStyle: {
    color: 'rgb(53,53,53)',
    fontSize: '14@ms',
    lineHeight: '22@ms',
    borderBottomColor: '#ffffff',
    borderBottomWidth: 0.5,
    fontFamily: 'Inter-Regular',
  },
  textInputWrapper: {
    height: '68@ms',
    width: '100%',
    borderWidth: '2@ms',
    borderColor: constants.colors.OrangeColor,
    borderRadius: '5@ms',
    marginTop: '20@ms',
  },
});

export default styles;
