export {default as DishesCard} from './DishesCard';
export {default as SmallPastryScreen} from './SmallPastryScreen';
export {default as RollsScreen} from './RollsScreen';
export {default as CoffeeCookies} from './coffeeCookies';
export {default as BreadScreen} from './BreadScreen';
export {default as DishesDetailScreen} from './DishesDetailScreen';
export {default as Header} from './Header';
export {default as CartButton} from './CartButton';
export {default as TabBar} from './TabBar';
